name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Lint, Audit and Test
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
            - run: npm ci
            - run: npm run lint
            - run: npm audit --audit-level=moderate
            - run: npm test
